[package]
name = "giphy-alfredworkflow"
version = "3.0.4"
authors = ["Alpha Chen <alpha.chen@gmail.com>"]

[dependencies]
error-chain = "0.10"
rayon = "0.8"
reqwest = "0.7"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
url = "1.5"
url_serde = "0.2"
